// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgEbTIXhLpsZOBfXKRuIXNncLIu1W2Gzo',
    appId: '1:619944012706:web:b5e4813412a59d8eb8e0fb',
    messagingSenderId: '619944012706',
    projectId: 'word-battle-app',
    authDomain: 'word-battle-app.firebaseapp.com',
    storageBucket: 'word-battle-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrqZtGxar_85emKLvupPm_-2uwAThg1I',
    appId: '1:619944012706:android:05578b0e40c16c62b8e0fb',
    messagingSenderId: '619944012706',
    projectId: 'word-battle-app',
    storageBucket: 'word-battle-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKplZKMjyZufZvffPakr6dLl7_bxr7qA',
    appId: '1:619944012706:ios:2acc9365a377d3dcb8e0fb',
    messagingSenderId: '619944012706',
    projectId: 'word-battle-app',
    storageBucket: 'word-battle-app.firebasestorage.app',
    iosBundleId: 'com.example.wordBattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTKplZKMjyZufZvffPakr6dLl7_bxr7qA',
    appId: '1:619944012706:ios:2acc9365a377d3dcb8e0fb',
    messagingSenderId: '619944012706',
    projectId: 'word-battle-app',
    storageBucket: 'word-battle-app.firebasestorage.app',
    iosBundleId: 'com.example.wordBattle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}